name: Update README

on:
  schedule:
    - cron: '0 */1 * * *'
  push:
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Run update script
        run: npm start

      - name: Commit README
        run: |
          git config --local user.name 'Ju-MINJAE' 
          git config --local user.email 'juminjae98@gmail.com'
          if [ -n "$(git status --porcelain)" ]; then
            git add README.md
            git commit -m 'Update README with latest blog posts'
            git push
          else
            echo "No changes to commit"
          fi
        env:
          GH_PERSONAL_TOKEN: ${{ secrets.JU_PERSONAL_TOKEN }}
